#!/usr/bin/env php
<?php
/**
 * @copyright 2016 Martin Takáč (http://martin.takac.name)
 * @license   https://opensource.org/licenses/MIT MIT
 */

if (@!include __DIR__ . '/../../../vendor/autoload.php') {
	echo 'Install Application using `composer install`';
	exit(1);
}

require __dir__ . '/commands/HelloCommand.php';

use Taco\Console\AppFactory;

$app = AppFactory::create('0.0.1',
	'greating',
	'Ukázková aplikace. Smyslem je, definovat commandy bez žádného dalšího okecávání.

Commandy mohou a nemusí spolupracovat. Když spolupracují, tak můžeme použít továrničku, která nám usnadní vytvoření.
Všechny ty závislosti a přepínače se definují u commandu, a FW si je sám extrahuje.',
	null,
	[
		'Martin Takáč <martin@takac.name>',
		'Nermal Kowalski <kowalski@nermal.cz>',
	]
)->addCommand(App\Console\HelloCommand::class);
exit($app->run($GLOBALS));
