#!/usr/bin/env php
<?php
/**
 * Copyright (c) 2004, 2015 Martin Takáč
 * @author     Martin Takáč <taco@taco-beru.name>
 */

require __dir__ . '/../../../vendor/autoload.php';
require __dir__ . '/commands/HelloCommand.php';
require __dir__ . '/commands/VersionCommand.php';

use Taco\Console;

$app = new Console\Runner(new Console\NetteContainer(__dir__ . '/config.neon', __dir__ . '/../../../temp'));
exit($app->run($GLOBALS));
